### PR TITLE
Add Docusaurus site source

### PR DESCRIPTION
**Pull request by ptgott**

### CODE REVIEW

**Review by taraspos — APPROVED** [review]

**Comment by taraspos** [comment]
@ptgott favicon contains an old logo:
- https://github.com/gravitational/docs-website/blob/7f3d418020dae86574a25dd25bd4b7bd3ed6cb41/static/favicon.svg

**Review by taraspos — CHANGES_REQUESTED** [review]
Update favicon to us new logo:
- https://github.com/gravitational/docs-website/blob/7f3d418020dae86574a25dd25bd4b7bd3ed6cb41/static/favicon.svg

**Comment by ptgott** [comment]
> Update favicon to use new logo:
> 
> * https://github.com/gravitational/docs-website/blob/7f3d418020dae86574a25dd25bd4b7bd3ed6cb41/static/favicon.svg

Fixed in ecc8d3fd9af540c75aad780e6751a6873712aa3e

**Review by taraspos — APPROVED** [review]

**Comment by ptgott** [comment]
@mmcallister Are you able to review this one so we can merge the Docusaurus source?

**Review by mmcallister — APPROVED** [review]

**Comment by taraspos** [comment]
@ptgott seems like it won't work unless we copy following GHA:
- https://github.com/gravitational/docs/blob/main/.github/workflows/codeql.yml
- https://github.com/gravitational/docs/blob/main/.github/workflows/dependency-review.yaml

**Pull request merged**
